### ISSUE TITLE
Integration of OpenAPI in Mida Node.js Framework

### ISSUE THREAD

**Issue by Vasile-Peste** [spotware/OpenAPI.Net#2]
Hi, I'm creating a Node.js framework for automatically operating in financial markets: https://github.com/Reiryoku-Technologies/Mida.

I understand that you are allowing this through the OpenAPI referenced at:
https://connect.spotware.com/docs/open_api_2

I have a question:
1. Am I allowed to integrate your API in my framework and allow users to login in their cTrader broker accounts to operate?

Thank you.

**Comment by amusleh-spotware-com** [comment]
Hi,

Yes, you can integrate cTrader on your platform via Open API.

Please check our new documentation for Open API: https://spotware.github.io/open-api-docs/

If you need any help or had any question you can contact me via Telegram: [@algodeveloper](https://t.me/algodeveloper)
