### ISSUE TITLE
Console.Sample using Windows specific method to open authUri

### ISSUE THREAD

**Issue by vijayganeshpk** [spotware/OpenAPI.Net#23]
When going through the file `samples/Console.Sample/Program.cs` came across the following code at line `88`:

```csharp
System.Diagnostics.Process.Start("explorer.exe", $"\"{authUri}\"");
```

Since this is valid only on Windows, it can be wrapped in an if statement checking

```csharp
System.OperatingSystem.IsWindows()
```

For the rest of the operating systems, the final `authUri` can be printed to the console or appropriate process can be opened (in MacOS it would be `open` command).

**Comment by amusleh-spotware-com** [comment]
@vijayganeshpk Can you open a PR for this?
