### ISSUE TITLE
ProtoOAAccountAuthReq hangs when called

### ISSUE THREAD

**Issue by paolobriones** [spotware/OpenAPI.Net#25]
I've come across an issue with the library where calling **ProtoOAAccountAuthReq** does not return any response, no errors or anything, it just waits for a response indefinitely. (The initial request to **ProtoOAApplicationAuthReq** always succeeded.)

**_This issue doesn't happen all the time, I feel like it only occurs if there is a deployment ongoing on the Spotware side, I'm not sure. I've seen this happen several times in the past and usually fixes itself after a few hours._**

I have figured out the cause of the issue, and it has something to do with the proxy URL returned by **ApiInfo.GetInfo(Mode)**. The GetInfo() method returns "**demo.ctraderapi.com**" or "**live.ctraderapi.com**".

however, based on the **Proxies/Endpoints** documentation (https://help.ctrader.com/open-api/proxies-endpoints/), there are several region-specific servers that should be used, such as "**demo-sg.ctraderapi.com**" or "**live-sg.ctraderapi.com**".

Since I started using this library, the examples specify that the way to initialize the SpotwareClient object should be done like this:

`OpenClient client = new(ApiInfo.GetHost(Mode.Demo), ApiInfo.Port, TimeSpan.FromSeconds(10)); `

Which would return the "demo.ctraderapi.com" or "live.ctraderapi.com" URL. 

**_The fix is to not use ApiInfo at all during initialization of the OpenClient object, instead, either retrieve the region-specific URL from your database or hardcode the URL during ctor initialization._**

I am currently using v1.4.4 of this library.

Maybe an update to the ApiInfo code should be done to support these region-specific API servers?

**Comment by paolobriones** [comment]
On the Proxies/Endpoints documentation page, there was this note about connection issues to the API servers:

![image](https://user-images.githubusercontent.com/8637626/192072582-519119c4-107b-4f93-989b-183860c3e7fa.png)

Maybe this ApiInfo.GetHost() is the cause of the issues when using this library?

**Comment by amusleh-spotware-com** [comment]
Hi @paolobriones,

ApiInfo was designed when we only had two proxy, now we have separate proxies for each region and if you use ApiInfo class it will give you one of the old proxies.

I will close this issue, if you want to you can change ApiInfo class and open a PR.
