### ISSUE TITLE
Any plans for python examples? 

### ISSUE THREAD

**Issue by pavitrakumar78** [spotware/OpenAPI.Net#3]
Hi,

I've been testing out the API with python, but I'm having some trouble with getting the initial authorization working. Would it be ok if I share the code here, work on it and once it works, clean it up and put it up as a simple python examples repository for OpenAPI? 

Thanks!

**Comment by amusleh-spotware-com** [comment]
Hi,
We will develop a Python package for Open API like we have one for .NET.
We can't give you any ETA right now.
